### ISSUE TITLE
考虑将该项目核心脚本发布为一个 GitHub Actions 吗？

### ISSUE THREAD

**Issue by wangrunlin** [Yuyz0112/vx.dev#104]
这样就可以让任何现有前端仓库通过 GitHub Actions 使用 vx.dev 的编程方式

- https://github.com/features/actions

@Yuyz0112

**Comment by Yuyz0112** [comment]
可以的，但是可能等整体功能再丰富和稳定一段时间再做这个抽象。

**Comment by wangrunlin** [comment]
好的，我们团队已经在开始试用了，会考虑将该项目未来的 GitHub Actions 集成到我们的 [核心前端脚手架](https://github.com/idea2app/Next-Bootstrap-ts) 中，之后会考虑回馈上游。

**Comment by TechQuery** [comment]
> 可以的，但是可能等整体功能再丰富和稳定一段时间再做这个抽象。

有人一年前先占了个坑，但也没写什么实质性的东西：https://github.com/matsubo/write-code-and-create-pr-from-issue-by-chatgpt
