### ISSUE TITLE
a thank you page for eli cohen for finding this 

### ISSUE THREAD

**Issue by MendyLanda** [Yuyz0112/vx.dev#142]
A slick modern looking one page thank you website for finding a cool generative AI open source repo for generating  UI

**Comment by MendyLanda** [comment]
wrong repo :)

**Comment by Yuyz0112** [comment]
@MendyLanda Hi, you can experience it three times after star this repo.

**Comment by MendyLanda** [comment]
> @MendyLanda Hi, you can experience it three times after star this repo.

I appreciate it, already forked it and have it working with my own key. This repo deserve a star regardless 🫶
