### ISSUE TITLE
关于实现原理的一些问题

### ISSUE THREAD

**Issue by seeflood** [Yuyz0112/vx.dev#88]
您好，我是您的b站老粉，对实现原理有一些疑问，想请教下

1. 我对[architecture.md里介绍的“通过分析语法树来修复import 错误”](https://github.com/Yuyz0112/vx.dev/blob/main/docs/architecture.md#code-generation-optimization) 很感兴趣
> After reverse-engineering v0.dev's approach, we've developed a method to correct these issues by analyzing the code's AST.

我去看了[实现代码](https://github.com/Yuyz0112/vx.dev/blob/a9a3f9d78251888159a61656c146ed7c325bcfef/prompts/ui-gen.ts#L83) ，但是我前端水平有限，没太看懂……

能否展开介绍下这部分的原理? 

2. 文档上说生成 JSX 能提高稳定性，能否解释下 why? 意思是“生成静态类型的代码后，方便由工具链做自动验证”，还是“chatgpt 生成 JSX 代码 比生成 js 代码的正确率要高"?

> An important learning from v0.dev is to generate entirely static JSX code, which, despite seemingly limiting use cases, significantly improves stability.

感谢!!

**Comment by Yuyz0112** [comment]
@seeflood 

第一点可以参考博客：https://juejin.cn/post/7316796251149090851 中的“秘籍：生成代码二次优化”。

具体来说就是 AI 会一直在一些地方重复犯错，通过 prompts 纠正效果有限，所以通过 AST 检查是否出现了“常见错误”，如果出现，使用对应的修复方式纠正。

第二点是指“**静态**JSX”提高了稳定性。这里的静态是指组件不接受外部的 props，逻辑完全内聚，符合 AI 擅长的 self-containerd 特性。
